[package]
name = "nat_hole_punch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.67"
hex = "0.4.3"
rlp = "0.5.2"
